RKB-205 RHEL-07-030360 Adds audit rules for 32- and 64-bit architectures
ampsight/RHEL7-STIG pull request #43
Opened 2018-12-04 17:58 UTC by PaulWaldo

2018-12-04 18:35 UTC, jvitray approved these changes
lgtm

2018-12-04 18:58 UTC, awilson61363 approved these changes
Looks good Paul.. let's merge

2018-12-04 18:59 UTC, robinje requested changes
[ansible@ip-172-16-30-99 RHEL7-STIG-paul-RHEL-07-030360]$ ansible-playbook -i /opt/ocp/ansible-hosts-3.11.16 -vv stig.yml
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible-playbook 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
statically imported: /home/ansible/RHEL7-STIG-paul-RHEL-07-030360/tasks/prelim.yml
statically imported: /home/ansible/RHEL7-STIG-paul-RHEL-07-030360/tasks/fix-cat1.yml
statically imported: /home/ansible/RHEL7-STIG-paul-RHEL-07-030360/tasks/fix-cat2.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/ansible/RHEL7-STIG-paul-RHEL-07-030360/tasks/fix-cat2.yml': line 1452, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


      - name: "MEDIUM | RHEL-07-030360 | Regenerate audit.rules file."
        ^ here

2018-12-04 21:22 UTC, awilson61363 approved these changes

2018-12-05 04:30 UTC, robinje approved these changes

2018-12-05 04:30 UTC, merged